name: testapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.4.0
  flutter_svg: ^2.0.7
  flutter_image_slideshow: ^0.1.5
  flat_3d_button: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
    - images/img/
    - images/menu/
    - images/buttonBar/


